[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/img/home/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[redirects]]
  from = "/cv"
  to = "/docs/cv.pdf"
  status = 200
